name: Update Reddit Data Hourly

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering for testing
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/update-data.yml'
      - 'scripts/fetch_reddit_data.py'

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install praw python-dotenv requests asyncpraw asyncio-throttle pandas numpy
    
    - name: Fetch Reddit data
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      run: |
        python scripts/fetch_reddit_data.py || echo "Reddit API unavailable, using sample data"
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/data/
        git diff --staged --quiet || (git commit -m "🤖 Auto-update Reddit data - $(date '+%Y-%m-%d %H:%M UTC')" && git push)

permissions:
  contents: write